name: GitHub Actions Demo

on:
  push

jobs:
  explore-github-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List repository files
        run: ls -la

      - name: Display current directory
        run: pwd